# .scrutinizer.yml
filter:
    excluded_paths:
        - 'tests/*'
        - 'bin/*'
checks:
    php: false
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
build:
    environment:
        php:
            version: 7.1       # Common versions: 5.4, 5.5, 5.6, 7.0, 7.1, or hhvm
