build:
    environment:
        php:
            version: 7.1
    project_setup:
        before:
            - mysql -e "CREATE DATABASE api_rest_slimphp"
            - mysql api_rest_slimphp < app/data/database.sql
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'
