language: php

php:
  - '7.1'
  - '7.2'
  - hhvm

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE api_rest_slimphp;'

before_script:
  - mysql api_rest_slimphp < app/data/database.sql
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml --whitelist src

after_success:
  - CODECLIMATE_REPO_TOKEN=5acc45b5f48d4ca2a5baa0d22ee9a10890b29a76b3ef34a936fdd0ba8c5d7ba8 vendor/bin/test-reporter
