language: php

php:
  - '5.6'
  - '7.1'

services:
  - mysql

before_install:
  - mysql -uroot -p -e 'CREATE DATABASE api_rest_slimphp;'

before_script:
  - mysql -uroot -p api_rest_slimphp < database.sql
  - composer install
