language: php

php:
  - '5.6'
  - '7.1'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE api_rest_slimphp;'

before_script:
  - mysql api_rest_slimphp < data/database.sql
  - composer install
