language: php

php:
  - '5.6'
  - '7.1'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE api-rest-slimphp;'

before_script:
  - mysql -uroot -p api-rest-slimphp < database.sql
  - composer install
