language: php

php:
  - '5.6'
  - '7.1'
  - hhvm

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE api_rest_slimphp;'

before_script:
  - mysql api_rest_slimphp < data/database.sql
  - composer install

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml --whitelist src

after_success:
  - CODECLIMATE_REPO_TOKEN=0e991e38f9941a6bfd8d7876880e8ed04eaf40529f1c120025668e6f5367284d vendor/bin/test-reporter
