version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rest-api-slim-php
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html
    links:
      - mysql
    environment:
      DB_HOSTNAME: mysql
      DB_DATABASE: rest_api_slim_php
      DB_USERNAME: app
      DB_PASSWORD: password
  mysql:
    image: mysql:5.7
    ports:
      - 33060:3306
    environment:
      MYSQL_DATABASE: rest_api_slim_php
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
